//
//  ViewController.swift
//  Tip Calculator


import UIKit

class ViewController: UIViewController {
    
    @IBOutlet weak var billAmountLabel: UILabel!
    @IBOutlet weak var customTipPercentLabel: UILabel!
    @IBOutlet weak var customTipPercentSlider: UISlider!
    @IBOutlet weak var tipCustomLabel: UILabel!
    @IBOutlet weak var totalCustomLabel: UILabel!
    @IBOutlet weak var inputTextField: UITextField!
    @IBOutlet weak var customNumberOfPeopleLabel: UILabel!
    @IBOutlet weak var customNumberOfPeopleSlider: UISlider!
    @IBOutlet weak var totalBillPerPersonLabel: UILabel!
    
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        self.view.backgroundColor = UIColor.black
        //Reinforce that the initial tip percent is 15%
        customTipPercentSlider.value = 15
        customNumberOfPeopleSlider.value = 5
        
        inputTextField.placeholder = "Enter Bill"
        
    }
    
    @IBAction func calculateTip(_ sender: Any) {
        var decimal100: Double
        decimal100 = 100.0
        var customPercent: Double
        var customNumberOfPeople: Int
        var billAmount: Double
        var inputDouble: Double
                
        //get user input
        let inputString = inputTextField.text
                
        //convert user input to Double
        inputDouble = Double((inputString! as NSString).floatValue)
                
        //convert slider value to a decimal number and store in a variable
        let sliderValue = Int(customTipPercentSlider.value)
        let numberOfPeople = Int(customNumberOfPeopleSlider.value)
                
        //convert the slider value to percent
        customPercent = Double(sliderValue)/decimal100
        
        //assign number of people to custom number of people
        customNumberOfPeople = numberOfPeople
                
        //identify who did generate the event. Was the slider?
        if sender is UISlider {
            //the thumb has been moved by the user, so update the label with the new custom percent
            customTipPercentLabel.text = NumberFormatter.localizedString(from: NSNumber(value:customPercent), number: NumberFormatter.Style.percent)
            customNumberOfPeopleLabel.text = NumberFormatter.localizedString(from: NSNumber(value:customNumberOfPeople), number: NumberFormatter.Style.none)
        }
                
        //if there's a bill amount, calculate the new tip and total
        if !inputString!.isEmpty {
            //convert the billAmount to add the decimal point
            billAmount = inputDouble/decimal100
                    
            //check if the event as generated by the TextField
            if sender is UITextField {
                //update the billAmount with the currency format
                billAmountLabel.text = " " + formatAsCurrency(number: billAmount)
    
            }
                    
            //calculate and display the tip and the total with currency format
            let customTip = billAmount * customPercent
            let billPerPersonAmount = (billAmount + customTip)/Double(numberOfPeople)
                tipCustomLabel.text = formatAsCurrency(number:customTip)
                totalCustomLabel.text = formatAsCurrency(number:billAmount + customTip)
                totalBillPerPersonLabel.text = formatAsCurrency(number:billPerPersonAmount)
            }
            else {
                //clear all labels
                billAmountLabel.text = " "
                customTipPercentLabel.text = NumberFormatter.localizedString(from: NSNumber(value: customPercent), number: NumberFormatter.Style.percent)
                tipCustomLabel.text = " "
                totalCustomLabel.text = " "
                totalBillPerPersonLabel.text = " "
            }
    }
    
}


func formatAsCurrency(number: Double) -> String {
    return NumberFormatter.localizedString(from: NSNumber(value:number), number: NumberFormatter.Style.currency)
}





